Test de la pipeline

diff --git a/.github/workflows/Version by PullRequest.yml b/.github/workflows/Version by PullRequest.yml
--- a/.github/workflows/Version by PullRequest.yml
+++ b/.github/workflows/Version by PullRequest.yml
@@ -43,31 +43,25 @@ jobs:
       - name: Fetch All Branches
         run: git fetch --all
 
+      - name: Checkout Main Branch
+        run: git checkout main
+
+      - name: Get Current Version from composer.json
+        id: get_version
+        run: |
+          if [ ! -f composer.json ]; then
+            echo "composer.json not found!"
+            exit 1
+          fi
+          current_version=$(jq -r '.version' composer.json)
+          if [[ -z "$current_version" || "$current_version" == "null" ]]; then
+            current_version="0.0.0"
+          fi
+          echo "Current version in main branch: $current_version"
+          echo "::set-output name=current_version::$current_version"
+
       - name: Checkout Pull Request Branch
         run: git checkout ${{ github.head_ref }}
-
-      - name: Extract Version from Last PR Title
-        id: extract_version
-        run: |
-          response=$(curl -s -H "Authorization: token ${{ secrets.API_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls?state=closed&sort=updated&direction=desc&per_page=100")
-          echo "API Response: $response"
-
-          latest_pr_titles=$(echo "$response" | jq -r '.[].title')
-          echo "Latest PR Titles: $latest_pr_titles"
-
-          version=""
-          while read -r title; do
-            echo "Processing title: $title"
-            extracted_version=$(echo "$title" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
-            if [[ ! -z "$extracted_version" ]]; then
-              version="$extracted_version"
-              break
-            fi
-          done <<< "$latest_pr_titles"
-          [[ -z "$version" ]] && version="0.0.0"
-
-          echo "Extracted Version: $version"
-          echo "::set-output name=version::$version"
 
       - name: Extract Current PR Title
         id: pr_info
@@ -79,7 +73,7 @@ jobs:
         id: update_version
         run: |
           title="${{ steps.pr_info.outputs.title }}"
-          version="${{ steps.extract_version.outputs.version }}"
+          version="${{ steps.get_version.outputs.current_version }}"
           if [[ $title == *"Majeur"* ]]; then
               version=$(echo $version | awk -F. '{$1++; $2=0; $3=0} 1' OFS=.)
           elif [[ $title == *"Mineur"* ]]; then
